new-minutes: 60
new-message: "<white>• <#91d1bd><player> <#5d9d88>is new and has keep-inventory for <#91d1bd><remaining>m<#5d9d88>."

killed-announce: "<white>• <#e2b492><player> <#b98863>has keep-inventory <#b98863>(<#e2b492><remaining>m<#b98863>) so no drops."
killing-announce: "<white>• <#e2b492><attacker> <#b98863>has keep-inventory <#b98863>(<#e2b492><remaining>m<#b98863>) so <#e2b492><defender> <#b98863>dropped nothing."

timer-remove-keep: "<#846d91>You've played 1h! <br><#c0a1d1>Your keep-inventory has been removed."
staff-timer-remove-keep: "<#757575><player> played 1h. <br><#757575>KI removed."

end-entry-blocked: "<#e06565>You can't enter The End with keep-inventory! <br><#e37f7f>Wait <remaining>m."
staff-end-entry-blocked: "<#757575><player> tried to enter The End with KI – blocked. (<remaining>m)"

pvp-inform: "<#c0a1d1>You have keep-inventory - players you kill <#f1d6ff>won't drop items<#c0a1d1> either."
pickup-inform: "<#c0a1d1>Only you can pick that up for <#f1d6ff>8s<#c0a1d1>. <br><#846d91>this pickup priority ends in <#f1d6ff><remaining>m<#846d91>."
feather-inform: "<#e06565>Did someone tell you to drop your feather? <br><#e06565>They're tricking you—pick it up! <br><#e37f7f>/tip feather"
